### ISSUE TITLE
京豆折线明细显示bug

### ISSUE THREAD

**Issue by BIGBbox** [anker1209/Scriptable#12]
![3f5acef00c1b7f2d6e549a3f645a4e6](https://user-images.githubusercontent.com/52786394/120422384-b7257f80-c39a-11eb-8c6f-8893cccc0777.jpg)

如图,十二点多的时候打开过一次,出现了双折线,尝试了重置数据,也没有解决

**Comment by anker1209** [comment]
并非bug，而是你设置了一张背景图片
