### ISSUE TITLE
京东小组件的头像不显示

### ISSUE THREAD

**Issue by chiperman** [anker1209/Scriptable#8]
![image](https://user-images.githubusercontent.com/34889778/110237499-665ae200-7f77-11eb-8a82-d9f172d89a90.png)
![image](https://user-images.githubusercontent.com/34889778/110237514-74106780-7f77-11eb-8f3a-31debf515f16.png)

请问应该如何解决？

**Comment by anker1209** [comment]
你京东有头像嘛？没有的话去京东app上传头像，然后清除缓存，运行脚本。
